language: android
env:
  global:
    - MALLOC_ARENA_MAX=2
sudo: required
android:
  components:
  - build-tools-23.0.1
  - android-22
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
script:
- "./gradlew :app:assembleDebug"
deploy:
  provider: releases
  api_key: c6aeec96a35d3f6d8099f4ed6e5b7917a6b45330
  file: 'app/build/outputs/apk/app-debug.apk'
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
